name: pdfviewer_custom_search
description: A Flutter application that demonstrates how to create a custom search toolbar and perform text search operation using Flutter PDF Viewer.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  syncfusion_flutter_pdfviewer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true